# Generated by Django 4.1.3 on 2023-04-30 15:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Family Visit', 'Family Visit'), ('Bussiness', 'Bussineess'), ('Pilgrimage', 'Pilgrimage'), ('Health Purpose', 'Health Purpose'), ('Adventure', 'Adventure'), ('Academics', 'Academics')], max_length=200)),
                ('tour_Purpose', models.CharField(max_length=100)),
                ('Destination', django_countries.fields.CountryField(max_length=2)),
                ('continent', models.CharField(max_length=100)),
                ('tour_description', models.TextField(blank=True, null=True)),
                ('tour_transport_mode', models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('Flight', 'Flight'), ('Water Transport', 'Water Transport')], max_length=100)),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad')], max_length=200)),
            ],
        ),
    ]
